runtime: python37
#env: flex
entrypoint: gunicorn -b :$PORT main:app #--timeout 120 --preload

#runtime_config:
#  python_version: 3

beta_settings:
    cloud_sql_instances: pi-blog:asia-south1:pi-blog-sql-instance

env_variables:
  SECRET_KEY: 'cae026144a2b6e099648e464b1457bca'
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:GoB3rOvuuEaiuoLt@127.0.0.1/pi_blog_db?unix_socket=/cloudsql/pi-blog:asia-south1:pi-blog-sql-instance'
  CLOUD_SQL_CONNECTION_NAME: 'pi-blog:asia-south1:pi-blog-sql-instance'

#includes:
#- credentials.yaml